name: eisen
channels:
  - pytorch
  - conda-forge
  - pyg
  - defaults
dependencies:
  - python=3.9.12=h12debd9_1
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - torchvision=0.12.0=py39_cu113
  - numpy
  - pip=22.1.2=py39h06a4308_0
  - pytorch-sparse
  - pip:
    - itermplot==0.331
    - matplotlib==3.5.2
    - pandas==1.4.3
    - pillow==9.2.0
    - wandb==0.12.21
    - opencv-python==4.6.0.66
    - kornia==0.6.5
    - scikit-learn==1.1.1
    - scikit-image==0.19.3


